import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { createApp } from './server.js';
import { createCollector, positiveInteger } from './collector.js';
import { createStore } from './storage.js';
import { fetchSnapshot, runPulse } from './pulse.js';
const address='0x'+'a'.repeat(40);
const snapshot=(tvl=100)=>({timestamp:'2026-09-11T00:00:00Z',vaults:{1:{[address]:{name:'Vault',address,chainId:1,tvl,apy:-1,totalDepositors:10}}}});
function directory(t){const d=fs.mkdtempSync(path.join(os.tmpdir(),'pulse-collector-'));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));return d;}
function setup(t, options={}) {const d=options.directory??directory(t);const c=createCollector({directory:d,fetchCurrentSnapshot:async()=>snapshot(),...options});c.start({scheduled:false});t.after(()=>c.stop());return {c,d};}
async function api(t,c){const s=createApp({collector:c}).listen(0,'127.0.0.1');await once(s,'listening');t.after(()=>new Promise(r=>s.close(r)));return `http://127.0.0.1:${s.address().port}`;}
const flush=()=>new Promise(r=>setImmediate(r));

test('static frontend serves the official logo without proprietary fonts; source, storage and lock are private',async t=>{const {c}=setup(t);const u=await api(t,c);for(const p of ['/','/style.css','/app.js','/assets/brand/concrete-logo-dark.svg'])assert.equal((await fetch(u+p)).status,200);for(const p of ['/pulse.js','/data/latest.json','/data/pulse-state.json','/data/collector.lock','/assets/brand/Enduro-Regular.otf','/assets/brand/SuisseIntlMono.otf'])assert.equal((await fetch(u+p)).status,404);const html=fs.readFileSync('public/index.html','utf8'),css=fs.readFileSync('public/style.css','utf8');assert.ok(html.includes('/assets/brand/concrete-logo-dark.svg'));assert.ok(!css.includes('Enduro-Regular.otf'));assert.ok(!css.includes('SuisseIntlMono.otf'));assert.ok(!css.includes('@font-face'));assert.equal(c.metadata().ready,false);});
test('API reads, including simultaneous requests, never collect or advance storage',async t=>{let calls=0;const {c,d}=setup(t,{fetchCurrentSnapshot:async()=>{calls++;return snapshot(calls*100);}});await c.collect();await c.collect();const original=fs.readFileSync(path.join(d,'pulse-state.json'),'utf8');const u=await api(t,c);const replies=await Promise.all(Array.from({length:8},()=>fetch(u+'/api/pulse').then(r=>r.json())));assert.equal(calls,2);assert.equal(replies[0].summary.tvlChanges,1);assert.equal(replies[0].tvlChanges[0].change,100);assert.equal(replies[0].unavailableMetrics[0].metric,'apy');assert.ok(replies.every(r=>r.timestamp===replies[0].timestamp));assert.equal(fs.readFileSync(path.join(d,'pulse-state.json'),'utf8'),original);const h=await(await fetch(u+'/api/health')).json();assert.equal(h.ready,true);assert.equal(h.collecting,false);assert.equal(h.status,'ok');});
test('cold-start upstream failure returns generic 503 and health stays available',async t=>{const {c}=setup(t,{fetchCurrentSnapshot:async()=>{throw Error('secret path');}});await assert.rejects(c.collect());const u=await api(t,c);const r=await fetch(u+'/api/pulse');assert.equal(r.status,503);assert.equal(r.headers.get('retry-after'),'30');const b=await r.json();assert.equal(b.freshness.ready,false);assert.equal(b.freshness.state,'upstream-error');assert.ok(!JSON.stringify(b).includes('secret'));assert.equal((await fetch(u+'/api/health')).status,200);});
test('failure preserves last result and timestamps, marks stale, and recovers',async t=>{let fail=false;const {c,d}=setup(t,{fetchCurrentSnapshot:async()=>{if(fail)throw Error('offline');return snapshot();}});await c.collect();const first=c.read();const original=fs.readFileSync(path.join(d,'pulse-state.json'),'utf8');fail=true;await assert.rejects(c.collect());assert.equal(c.read().timestamp,first.timestamp);assert.deepEqual(c.read().summary,first.summary);assert.equal(c.metadata().stale,true);assert.equal(fs.readFileSync(path.join(d,'pulse-state.json'),'utf8'),original);fail=false;await c.collect();assert.equal(c.metadata().stale,false);});
test('collector triggers join one operation and shutdown cancels it without a commit',async t=>{let calls=0;const {c,d}=setup(t,{fetchCurrentSnapshot:({signal})=>new Promise((resolve,reject)=>{calls++;signal.addEventListener('abort',()=>reject(Error('aborted')));})});const a=c.collect(),b=c.collect();assert.equal(a,b);assert.equal(calls,1);assert.equal(c.metadata().collecting,true);await c.stop();await assert.rejects(a);await assert.rejects(c.collect(),/stopped/);assert.equal(fs.existsSync(path.join(d,'pulse-state.json')),false);});
test('SDK timeout calls actual abort and rejects',async t=>{t.mock.timers.enable({apis:['setTimeout']});let aborted=false,reject;const promise=new Promise((r,j)=>{reject=j;});const p=fetchSnapshot({timeoutMs:15000,requestFactory:()=>({abort(){aborted=true;reject(Error('aborted'));},toPromise:()=>promise})});const rejected=assert.rejects(p,/aborted/);t.mock.timers.tick(15000);await rejected;assert.equal(aborted,true);});
test('SDK late success after cancellation cannot become a snapshot',async t=>{t.mock.timers.enable({apis:['setTimeout']});let resolve,aborted=false;const p=fetchSnapshot({timeoutMs:15,requestFactory:()=>({abort(){aborted=true;},toPromise:()=>new Promise(r=>{resolve=r;})})});t.mock.timers.tick(15);resolve({});await assert.rejects(p,/cancelled/);assert.equal(aborted,true);});
test('scheduled startup, interval, and shutdown use one bounded timer',async t=>{let calls=0,callback,cleared=false;const c=createCollector({directory:directory(t),intervalMs:300000,fetchCurrentSnapshot:async()=>{calls++;return snapshot();},schedule:(fn,ms)=>{assert.equal(ms,300000);callback=fn;return 1;},unschedule:()=>{cleared=true;}});t.after(()=>c.stop());c.start();await flush();assert.equal(calls,1);callback();await flush();assert.equal(calls,2);await c.stop();callback();await flush();assert.equal(calls,2);assert.equal(cleared,true);});
test('restart restores exact comparison and delays collection for fresh state',async t=>{const {c,d}=setup(t);await c.collect();const original=c.read();await c.stop();let delay,calls=0;const restarted=createCollector({directory:d,intervalMs:300000,fetchCurrentSnapshot:async()=>{calls++;return snapshot();},schedule:(fn,ms)=>{delay=ms;return 1;},unschedule:()=>{}});t.after(()=>restarted.stop());restarted.start();assert.deepEqual(restarted.read().summary,original.summary);assert.equal(restarted.read().timestamp,original.timestamp);assert.equal(calls,0);assert.ok(delay>0);});
test('corrupt current generation recovers backup; staging files are ignored',async t=>{const {c,d}=setup(t);await c.collect();await c.collect();await c.stop();fs.writeFileSync(path.join(d,'pulse-state.json'),'broken');fs.writeFileSync(path.join(d,'pulse-state.json.tmp'),'partial');const recovered=createCollector({directory:d});assert.equal(recovered.metadata().ready,true);assert.equal(recovered.read().hasPreviousSnapshot,false);await recovered.stop();});
test('all malformed generations fail closed and remain untouched',async t=>{const d=directory(t);fs.writeFileSync(path.join(d,'pulse-state.json'),'broken');const {c}=setup(t,{directory:d});await assert.rejects(c.collect(),/recovery/);assert.equal(c.metadata().state,'storage-error');assert.equal(fs.readFileSync(path.join(d,'pulse-state.json'),'utf8'),'broken');});
test('interrupted atomic rename cannot replace last valid generation',async t=>{const {c,d}=setup(t);await c.collect();const original=fs.readFileSync(path.join(d,'pulse-state.json'),'utf8');const rename=fs.renameSync;const m=t.mock.method(fs,'renameSync',(from,to)=>{if(to===path.join(d,'pulse-state.json'))throw Error('disk failure');return rename(from,to);});await assert.rejects(c.collect(),/disk failure/);m.mock.restore();assert.equal(fs.readFileSync(path.join(d,'pulse-state.json'),'utf8'),original);assert.equal(createStore(d).load().current.vaults[1][address].tvl,100);assert.equal(fs.existsSync(path.join(d,'pulse-state.json.tmp')),false);});
test('second collector and CLI cannot acquire the writer lock',async t=>{const {c,d}=setup(t);const second=createCollector({directory:d});assert.throws(()=>second.start(),/EEXIST/);await assert.rejects(runPulse({print:false,snapshotDirectory:d}),/EEXIST/);await second.stop();assert.equal(fs.existsSync(path.join(d,'collector.lock')),true);await c.stop();assert.equal(fs.existsSync(path.join(d,'collector.lock')),false);});
test('legacy snapshots import without altering raw source and CLI uses new generation',async t=>{const d=directory(t);const raw=JSON.stringify(snapshot());fs.writeFileSync(path.join(d,'latest.json'),raw);const r=await runPulse({print:false,snapshotDirectory:d,fetchCurrentSnapshot:async()=>snapshot(150)});assert.equal(r.tvlChanges[0].change,50);assert.equal(fs.readFileSync(path.join(d,'latest.json'),'utf8'),raw);const state=createStore(d).load();assert.equal(state.current.vaults[1][address].apy,-1);assert.equal(state.previous.vaults[1][address].tvl,100);});
test('invalid configuration is rejected',()=>{for(const value of ['0','-1','oops','1.5','Infinity'])assert.throws(()=>positiveInteger(value,100,'test'));assert.equal(positiveInteger(undefined,300000,'test'),300000);});

test('SDK cancellation reaches native fetch signal and preserves collector state',async t=>{
    let aborted=false;
    t.mock.method(globalThis,'fetch',(_url,{signal})=>new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>{aborted=true;reject(Error('aborted'));});}));
    const {c}=setup(t,{timeoutMs:5,fetchCurrentSnapshot:fetchSnapshot});
    await assert.rejects(c.collect(),/aborted/);
    assert.equal(aborted,true);assert.equal(c.metadata().ready,false);
});
test('invalid upstream snapshot cannot overwrite successful generation',async t=>{
    let invalid=false;const {c,d}=setup(t,{fetchCurrentSnapshot:async()=>invalid?{timestamp:'bad',vaults:null}:snapshot()});
    await c.collect();const original=fs.readFileSync(path.join(d,'pulse-state.json'),'utf8');invalid=true;
    await assert.rejects(c.collect());assert.equal(fs.readFileSync(path.join(d,'pulse-state.json'),'utf8'),original);
});
test('storage is reloaded after acquiring exclusive ownership',async t=>{
    const {c,d}=setup(t);const next=createCollector({directory:d,fetchCurrentSnapshot:async()=>snapshot(200)});
    await c.collect();await c.stop();next.start({scheduled:false});t.after(()=>next.stop());
    await next.collect();assert.equal(next.read().tvlChanges[0].change,100);
});
